### ISSUE TITLE
Use PCA embedding as input data? 

### ISSUE THREAD

**Issue by grst** [GregorySchwartz/too-many-cells#1]
Hi @GregorySchwartz,

this tool looks pretty awesome, I'm curious to try it out!

From the documentation I understand that `too-many-cells` expects a (UMI)-count matrix. 
Would the algorithm also work with embedded data (e.g. PCA)? 

I am asking because I have a large single cell dataset integrated from different sources and I performed some data cleaning/batch effect removal steps that work on embedded data. 

Cheers, 
Gregor

**Comment by GregorySchwartz** [comment]
Yes, it can work with any matrix! I won't make any guarantees about how long it takes, though. If you preprocess your matrix, be sure to disable normalization (`--normalization NoneNorm`) and filterings (`--no-filter`). If taking too long from the dense matrix, try it out with the sparse matrix without PCA, it might worth it.

**Comment by GregorySchwartz** [comment]
As an update to this, I did not account for negative abundances. However, I have switched to using a signed Laplacian for the spectral clustering which should resolve this issue. Otherwise, the NaNs (from the inverse square root of the negatives) would have led to SVDLIBC hanging. For instance, I ran `too-many-cells` on your PCA data and it was taking forever. Switching to signed Laplacian now has it take literally a second. I will re-open this issue until I release a new version with a new docker. I should note that I have not altered the modularity calculation.

**Comment by GregorySchwartz** [comment]
Solved in https://github.com/GregorySchwartz/spectral-clustering/commit/12175d1bce7872783b57a51f7a9cc2fea6b44b43 and in `too-many-cells-0.1.1.0`. Waiting for docker.

**Comment by GregorySchwartz** [comment]
Docker version uploaded to [https://cloud.docker.com/repository/docker/gregoryschwartz/too-many-cells/general](https://cloud.docker.com/repository/docker/gregoryschwartz/too-many-cells/general). This version includes `--dense` to use BLAS/LAPACK for clustering. May be faster for dense matrices.

**Comment by grst** [comment]
> However, I have switched to using a signed Laplacian for the spectral clustering which should resolve this issue. Otherwise, the NaNs (from the inverse square root of the negatives) would have led to SVDLIBC hanging.

Thanks for the update! That explains why it didn't make any progress running for hours on 32 CPUs... Now it works really fast!
There still seems to be a minor issue though (see #3).
