### ISSUE TITLE
Seurat SCtransform

### ISSUE THREAD

**Issue by dekan-aleksandr** [GregorySchwartz/too-many-cells#48]
Hello developers of too-many-cells! 
Could I use SCtranfrom normalized values as input? Does it contradict the assumptions of your algorithm?

**Comment by GregorySchwartz** [comment]
The underlying model uses cosine similarity between feature vectors to define similar cells. If that is not appropriate for with SCtransform, then it should not be used, but otherwise it should be fine. Just make sure to disable TooManyCells normalizations / filtering if you are already providing that.
